<a href="https://colab.research.google.com/github/officialaryansingh/pandas_learning/blob/main/pandas_fundamental2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#****Pandas Library :****
-useful for Data Processing & Analysis

##Pandas Data Frame:
-pandas DataFrame is two-dimentional tabular data structure with labeled axes (rows and columns).

In [29]:
# importing the pandas library
import pandas as pd
import numpy as np

Creating Padas DataFrame

In [16]:
# importing the calafornia_housing data set
from sklearn.datasets import fetch_california_housing

In [17]:
california_dataset = fetch_california_housing()

In [18]:
type(california_dataset)

sklearn.utils._bunch.Bunch

In [19]:
print(california_dataset)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [20]:
# pandas DataFrame
california_dataset_df = pd.DataFrame(data=california_dataset.data, columns=california_dataset.feature_names)

In [21]:
california_dataset_df.head() # this prints the 1st 5 rows of the dataFrame

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [22]:
california_dataset_df.shape

(20640, 8)

# importing the data from a CSV file to a pandas DataFrame

In [23]:
#  csv file to pandas df

housing_df = pd.read_csv("/content/housing.csv")

In [24]:
type(housing_df)

pandas.core.frame.DataFrame

In [25]:
housing_df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [26]:
type(california_dataset_df)

pandas.core.frame.DataFrame

Loading the excel file to the pandas DataFrame

Pd.read_excel('file path')

Exporting a DataFrame to a csv file

In [27]:
california_dataset_df.to_csv('california.csv')

Exporting the pandas DataFrame to an excel :

df.to_excel('filename')

In [30]:
# creating a dataframe with a random values
random_df = pd.DataFrame(np.random.rand(20,10))

In [31]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.200065,0.236917,0.113976,0.856331,0.952913,0.634899,0.750744,0.396049,0.832257,0.545635
1,0.262152,0.961107,0.671967,0.016427,0.874935,0.010576,0.725197,0.804521,0.449865,0.633596
2,0.354401,0.691628,0.695685,0.702996,0.560776,0.611047,0.017826,0.695700,0.958911,0.238148
3,0.011105,0.939266,0.877735,0.143053,0.248321,0.965572,0.474285,0.278381,0.314374,0.818204
4,0.126173,0.328970,0.821751,0.933159,0.111254,0.324312,0.622178,0.070621,0.631101,0.880420

In [32]:
random_df.shape

(20, 10)

In [33]:
california_dataset_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [34]:
california_dataset_df.tail() # This prints the last 5 rows of the DataFrame

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [36]:
# information about the DataFrame
california_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [37]:
# findong the number of missing values
california_dataset_df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [38]:
# housing DataFrame

housing_df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [39]:
housing_df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [40]:
# counting the values based on the labels -df.value_counts('name of the column name)

housing_df.value_counts('parking')

parking
0    299
1    126
2    108
3     12
Name: count, dtype: int64

In [45]:
'''group the values basrd on there mean

housing_df.groupby('parking').mean() - this shows error as housing dataset
contains string values and cannot be grouped together.Therefore, .mean() cannnot
be used

so we need to first

'''

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
random_df.to_excel('random.csv')